version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  check1:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run : python sample.py
      
  hold:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run : echo "Hold"
      
  check2:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run : python sample.py
workflows:
  main:
    jobs:
      - check1
      - hold:
          type: approval
          requires:
            - check1
      - check2:
          requires:
            - hold
